### ISSUE TITLE
The checkpoints folder does not contain files required to run the preprocessing code

### ISSUE THREAD

**Issue by gphilip** [mahmoodlab/FISH#1]
I tried to run the preprocessing steps listed in the **Usage** section of the description. Step 2 worked as described, but Step 3 failed because the script couldn't find the file `trash_lgrlbp.pkl` in the `checkpoints` folder. The failure occurs at the following lines in `extract_mosaic.py` : 

```
with open("./checkpoints/trash_lgrlbp.pkl", 'rb') as handle:
    clf = pickle.load(handle)
```

The file `checkpoints/CHECKPOINTS.md` suggests that this folder is supposed to contain some other files as well; none of these files is present in the current version on GitHub.

Could you please add these files so that I can try running the code. Thank you!

**Comment by ChenChengKuan** [comment]
Hello
Thanks for the interest. For the checkpoints, you have to download them from the link mentioned in the Reproducibility section. I'll make the doc more clear

**Comment by gphilip** [comment]
Thank you for your reply. I was able to complete step 3 by following your instruction.
